# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kraina' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kraina

pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils', '~> 4.1.0'
pod 'FirebaseAnalytics'
pod 'FirebaseStorage'
pod 'FirebaseDatabase'
pod 'FirebaseFirestore'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'SnapKit', '~> 5.0.0'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'
pod 'GoogleSignIn'
pod 'Firebase'
pod 'GSKStretchyHeaderView'
pod 'UltraDrawerView'
pod 'SPStorkController'
pod 'SPLarkController'
pod 'FloatingPanel'
pod "AlignedCollectionViewFlowLayout"
pod 'FAPaginationLayout'
pod 'Kingfisher', '~> 7.0'


end
